/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nani.awalia.view;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import nani.awalia.db.KoneksiDatabase;

/**
 *
 * @author Muhammad Adif Fikri || 1910631170101
 */
public class viewPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewPenjualan
     */
    
    private DefaultTableModel model;
    
    public viewPenjualan() {
        initComponents();
        
        model = new DefaultTableModel();
        tabelPenjualan.setModel(model);
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("QTY");
        model.addColumn("SubTotal");
//        tampilDataPenjualan();
        tahunView.setText("2022");
        pemasukanView.setDisabledTextColor(Color.black);
        terjualView.setDisabledTextColor(Color.black);
        pemasukanView.disable();
        terjualView.disable();
    }

    public JComboBox<String> getBulanView() {
        return bulanView;
    }

    public void setBulanView(JComboBox<String> bulanView) {
        this.bulanView = bulanView;
    }

    public JTextField getPemasukanView() {
        return pemasukanView;
    }

    public void setPemasukanView(JTextField pemasukanView) {
        this.pemasukanView = pemasukanView;
    }

    public JTextField getTahunView() {
        return tahunView;
    }

    public void setTahunView(JTextField tahunView) {
        this.tahunView = tahunView;
    }

    public JTextField getTerjualView() {
        return terjualView;
    }

    public void setTerjualView(JTextField terjualView) {
        this.terjualView = terjualView;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenjualan = new javax.swing.JTable();
        cariView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bulanView = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        terjualView = new javax.swing.JTextField();
        pemasukanView = new javax.swing.JTextField();
        tahunView = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catatan Penjualan");

        tabelPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPenjualan);

        cariView.setText("Cari");
        cariView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Catatan Penjualan Bulan : ");

        bulanView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanViewActionPerformed(evt);
            }
        });

        jLabel2.setText("Detail Bulanan :");

        jLabel3.setText("Total Barang Terjual :");

        jLabel4.setText("Pemasukan Kotor :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemasukanView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(terjualView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(bulanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tahunView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cariView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bulanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariView)
                    .addComponent(jLabel2)
                    .addComponent(tahunView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(terjualView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pemasukanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bulanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanViewActionPerformed

    private void cariViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariViewActionPerformed
        // TODO add your handling code here:
        int bulan = bulanView.getSelectedIndex() + 1;
        int terjual = 0;
        int pemasukan = 0;
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * FROM transaksiDetail WHERE tanggal >= '"+tahunView.getText()+"-"+bulan+"-1' AND tanggal <= '"
                +tahunView.getText()+"-"+bulan+"-31'";
        
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while (res.next()) {                
                Object[] hasil;
                hasil = new Object[4];
                hasil[0] = res.getString("tanggal");
                hasil[1] = res.getString("namaBarang");
                hasil[2] = res.getString("qty");
                hasil[3] = res.getString("subTotal");
                
                terjual = terjual + Integer.parseInt(res.getString("qty"));
                pemasukan = pemasukan + Integer.parseInt(res.getString("subTotal"));
                
                model.addRow(hasil);
            }
            terjualView.setText(Integer.toString(terjual)+" Pcs");
            pemasukanView.setText("Rp."+Integer.toString(pemasukan));
        } catch (SQLException e) {
            Logger.getLogger(viewPelangganInternal.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_cariViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bulanView;
    private javax.swing.JButton cariView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pemasukanView;
    private javax.swing.JTable tabelPenjualan;
    private javax.swing.JTextField tahunView;
    private javax.swing.JTextField terjualView;
    // End of variables declaration//GEN-END:variables
}
